export const LANE_OPTIONS = [1, 2, 3, 4, 5, 6];

export const MAXSPEED_OPTIONS: Record<string, string> = {
  "": "Not specified",
  "20": "20 km/h",
  "30": "30 km/h",
  "40": "40 km/h",
  "50": "50 km/h",
  "60": "60 km/h",
  "70": "70 km/h",
  "80": "80 km/h",
  "90": "90 km/h",
  "100": "100 km/h",
  "110": "110 km/h",
  "120": "120 km/h",
  "130": "130 km/h",
};

export const ONEWAY_OPTIONS: Record<string, string> = {
  "false": "No",
  "true": "Yes",
};

export type RoadTypeInfo = {
  color: string;
  description: string;
  freespeed: string;
  freespeedPct: number;
  modes: string;
  capacity: string;
  notes: string;
};

export const ROAD_TYPE_INFO: Partial<Record<string, RoadTypeInfo>> = {
  motorway: {
    color: "#ff6b6b",
    description: "Highest-capacity controlled-access highway. No cyclists or pedestrians by default.",
    freespeed: "120–140 km/h",
    freespeedPct: 95,
    modes: "car, motorbike",
    capacity: "Highest — per Swiss VSS 640 018a norms.",
    notes: "Motorway_link ramps use reduced speeds. One-way opposite links default to 1 lane.",
  },
  motorway_link: {
    color: "#ff8a80",
    description: "On/off ramps and slip roads connecting to motorways.",
    freespeed: "60–80 km/h",
    freespeedPct: 55,
    modes: "car, motorbike",
    capacity: "High — reduced from motorway.",
    notes: "Used for interchange ramps. Speed is reduced from the main carriageway.",
  },
  trunk: {
    color: "#ff9f43",
    description: "Most important non-motorway roads. Often inter-city corridors.",
    freespeed: "100–120 km/h",
    freespeedPct: 85,
    modes: "car, bike*",
    capacity: "Very high.",
    notes: "Need not be divided. Bike access permitted unless explicitly excluded.",
  },
  trunk_link: {
    color: "#ffb86b",
    description: "Slip roads and ramps connecting to trunk roads.",
    freespeed: "50–70 km/h",
    freespeedPct: 48,
    modes: "car, bike*",
    capacity: "High — reduced from trunk.",
    notes: "Connects trunk roads at interchanges.",
  },
  primary: {
    color: "#ffd32a",
    description: "Major roads linking cities and large towns. Often national or state routes.",
    freespeed: "80–100 km/h",
    freespeedPct: 70,
    modes: "car, bike, walk",
    capacity: "High.",
    notes: "In built-up areas, lower effective freespeed accounts for pedestrian crossings, traffic lights, and junction density.",
  },
  primary_link: {
    color: "#ffe066",
    description: "Slip roads connecting to primary roads.",
    freespeed: "40–60 km/h",
    freespeedPct: 40,
    modes: "car, bike, walk",
    capacity: "Moderate-high.",
    notes: "Connects primary roads at junctions or interchanges.",
  },
  secondary: {
    color: "#1dd1a1",
    description: "Roads connecting towns and larger villages. Typically county routes.",
    freespeed: "60–80 km/h",
    freespeedPct: 58,
    modes: "car, bike, walk",
    capacity: "Moderate-high.",
    notes: "Urban and rural variants use different default freespeeds to reflect typical junction density and roadside constraints.",
  },
  secondary_link: {
    color: "#55efc4",
    description: "Slip roads connecting to secondary roads.",
    freespeed: "30–50 km/h",
    freespeedPct: 35,
    modes: "car, bike, walk",
    capacity: "Moderate.",
    notes: "Connects secondary roads at junctions.",
  },
  tertiary: {
    color: "#54a0ff",
    description: "Minor roads connecting villages, or serving local through traffic.",
    freespeed: "50–70 km/h",
    freespeedPct: 48,
    modes: "car, bike, walk",
    capacity: "Moderate.",
    notes: "Often lack explicit maxspeed tags — road-type defaults apply.",
  },
  tertiary_link: {
    color: "#74b9ff",
    description: "Slip roads connecting to tertiary roads.",
    freespeed: "30–40 km/h",
    freespeedPct: 28,
    modes: "car, bike, walk",
    capacity: "Moderate-low.",
    notes: "Connects tertiary roads at junctions.",
  },
  residential: {
    color: "#a29bfe",
    description: "Primarily serves access to housing. Lower speeds; no through-traffic function.",
    freespeed: "30–50 km/h",
    freespeedPct: 30,
    modes: "car, bike, walk",
    capacity: "Low.",
    notes: "Urban by nature. Street-level capacity norms apply.",
  },
  unclassified: {
    color: "#fd79a8",
    description: "Least important through roads; not residential access.",
    freespeed: "40–60 km/h",
    freespeedPct: 40,
    modes: "car, bike, walk",
    capacity: "Low-moderate.",
    notes: "Catch-all for minor roads. May be rural or peri-urban.",
  },
  living_street: {
    color: "#55efc4",
    description: "Pedestrians have legal priority; vehicles allowed at walking speed.",
    freespeed: "7–15 km/h",
    freespeedPct: 8,
    modes: "car (very slow), bike, walk",
    capacity: "Very low.",
    notes: "Children may legally play in the street.",
  },
  service: {
    color: "#74b9ff",
    description: "Access roads within industrial estates, car parks, or private areas.",
    freespeed: "15–30 km/h",
    freespeedPct: 15,
    modes: "car, bike, walk",
    capacity: "Low.",
    notes: "Often not publicly accessible. Includes driveways and parking aisles.",
  },
  pedestrian: {
    color: "#dfe6e9",
    description: "Streets reserved primarily for pedestrians, typically in town centres.",
    freespeed: "4–8 km/h",
    freespeedPct: 4,
    modes: "walk (car access restricted)",
    capacity: "Minimal for vehicles.",
    notes: "Vehicles may be allowed at specific times.",
  },
  track: {
    color: "#b8860b",
    description: "Roads for agricultural or forestry use. Unpaved or rough surface.",
    freespeed: "20–40 km/h",
    freespeedPct: 20,
    modes: "car, bike, walk",
    capacity: "Low.",
    notes: "Grade may vary. Not suitable for regular traffic.",
  },
  cycleway: {
    color: "#6c5ce7",
    description: "Dedicated cycling path, separate from motor traffic.",
    freespeed: "15 km/h",
    freespeedPct: 12,
    modes: "bike",
    capacity: "Minimal in car simulations.",
    notes: "Fixed default unless maxspeed is tagged.",
  },
  footway: {
    color: "#b2bec3",
    description: "Dedicated pedestrian path, usually beside a road.",
    freespeed: "4 km/h",
    freespeedPct: 3,
    modes: "walk",
    capacity: "Minimal.",
    notes: "Steps use 2 km/h (0.556 m/s).",
  },
  path: {
    color: "#6c5ce7",
    description: "Generic walking and cycling infrastructure used for footpaths and bridleways.",
    freespeed: "2–15 km/h",
    freespeedPct: 5,
    modes: "bike, walk",
    capacity: "Minimal.",
    notes: "Steps = 2 km/h, walk-only = 4 km/h, bike = 15 km/h.",
  },
};
