FROM oven/bun:1-alpine

WORKDIR /app

COPY trafficjam-fe/package.json trafficjam-fe/bun.lock* ./

#RUN bun install --frozen-lockfile
RUN bun install

COPY trafficjam-fe/ .

RUN bun run build


EXPOSE 5173
CMD ["bun", "run", "preview","--host", "0.0.0.0", "--port", "5173"]
