FROM --platform=linux/amd64 postgis/postgis:18-3.6

# healthcheck to ensure the database is ready
HEALTHCHECK --interval=5s --timeout=5s --retries=5 \
    CMD pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
