FROM oven/bun:1-alpine
WORKDIR /app

ARG NODE_ENV=development

COPY trafficjam-fe/package.json trafficjam-fe/bun.lock* ./
RUN bun install --frozen-lockfile

COPY trafficjam-fe/ .

ENV NODE_ENV=${NODE_ENV}
RUN bun run build

EXPOSE 5173
CMD ["bun", "run", "preview","--host", "0.0.0.0", "--port", "5173"]
