FROM nats:2-alpine

COPY docker/nats-server.conf /etc/nats/nats-server.conf

HEALTHCHECK --interval=5s --timeout=5s --retries=5 \
    CMD wget --no-verbose --tries=1 --spider http://localhost:8222/healthz || exit 1

ENTRYPOINT ["nats-server"]
CMD ["--config", "/etc/nats/nats-server.conf"]
