package com.trafficjam.matsim;

import com.trafficjam.matsim.ConfigGenerator;
import com.trafficjam.matsim.MatsimRunner;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.*;

public class SimWrapperIntegrationTest {

    @TempDir
    Path tempDir;

    @Test
    void testSimWrapperDashboardsGeneratedAfterSimulation() throws Exception {
        // Locate test resources
        Path networkFile = Path.of("src/test/resources/cork_network_integration_test.xml");
        Path plansFile = Path.of("src/test/resources/cork_city_plans_integration_test.xml");

        assertTrue(Files.exists(networkFile), "Network file not found");
        assertTrue(Files.exists(plansFile), "Plans file not found");

        // Generate config pointing to temp output dir
        Path outputDir = tempDir.resolve("output");
        Files.createDirectories(outputDir);

        ConfigGenerator generator = new ConfigGenerator();
        String configContent = generator.generateConfig(
                networkFile.toAbsolutePath().toString(),
                plansFile.toAbsolutePath().toString(),
                "EPSG:2157",
                outputDir.toAbsolutePath().toString(),
                2,    // just 2 iterations to keep it fast
                42   // fixed seed for reproducibility
        );

        Path configPath = tempDir.resolve("config.xml");
        Files.writeString(configPath, configContent);

        // Run simulation async and wait for completion
        MatsimRunner runner = new MatsimRunner();
        CountDownLatch latch = new CountDownLatch(1);
        final MatsimRunner.SimulationState[] finalState = new MatsimRunner.SimulationState[1];

        runner.runSimulationAsync(
                configPath.toString(),
                event -> {}, // we don't care about events here
                (simId, status) -> {
                    if (status == MatsimRunner.SimulationState.COMPLETED
                            || status == MatsimRunner.SimulationState.FAILED) {
                        finalState[0] = status;
                        latch.countDown();
                    }
                }
        );

        // Wait up to 3 minutes for the simulation to finish
        boolean finished = latch.await(3, TimeUnit.MINUTES);

        assertTrue(finished, "Simulation timed out after 3 minutes");
        assertEquals(MatsimRunner.SimulationState.COMPLETED, finalState[0],
                "Simulation did not complete successfully");

        // Check that SimWrapper generated dashboard YAML files
        try (Stream<Path> files = Files.list(outputDir)) {
            long dashboardCount = files
                    .filter(p -> p.getFileName().toString().startsWith("dashboard-"))
                    .filter(p -> p.getFileName().toString().endsWith(".yaml"))
                    .count();

            System.out.println("=== SimWrapper Output Files ===");
            Files.list(outputDir).forEach(p -> System.out.println(p.getFileName()));
            System.out.println("================================");

            assertTrue(dashboardCount > 0,
                    "No dashboard-*.yaml files were generated by SimWrapperModule. " +
                    "Check that SimWrapperModule is registered in MatsimRunner.");
        }
    }
}